import type { Metadata } from "next";
import { Lisu_Bosa } from "next/font/google"; // Ensure the font is correctly imported
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import "./font2.css"

// Configure the font
const lisuBosa = Lisu_Bosa({
  variable: "--font-lisu-bosa",
  subsets: ["latin"],
  weight: ["400", "700"], // Add weights if applicable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lisuBosa.variable}>
      <body suppressHydrationWarning className={`dark:bg-[#022D5F] ${lisuBosa.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
